version: '3.1'
services:
  api:
    image: travel-office-web.jar
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/TravelOfficeWEBDL
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=INQOO
    volumes:
      - C/User/pg-docker:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 6






